#define WIDTH 60
#define HEIGHT 30
#define EMPTY_SPACE 0
#define WALL 1
#define SNAKE_HEAD 2
#define SNAKE_BODY 3
#define PLUSITEM 4
#define MINUSITEM 5
#define IMMUNE_WALL 6
#define GATE 10
#define ITEM_LIFE_TIME 8
#define ITEM_CYCLE 15
#define GATE_CYCLE 10
#define UP 259
#define RIGHT 261
#define LEFT 260
#define DOWN 258
